version: '3.8'

services:
  postgres:
    container_name: tehnologiinet-postgres
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: template
      PGDATA: /var/lib/postgresql/data
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "2345:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: tehnologiinet-pgadmin
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: